<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="LAPTOP-0NT22F0F" failures="1" tests="3" name="com.crm.qa.testcases.BaseUrlTest" time="13.415" errors="0" timestamp="2022-09-19T17:33:34 BST" skipped="0">
  <testcase classname="com.crm.qa.testcases.BaseUrlTest" name="T01_clickLoginTest" time="5.696"/>
  <system-out/>
  <testcase classname="com.crm.qa.testcases.BaseUrlTest" name="T02_BaseUrlPageLogoTest" time="5.474"/>
  <system-out/>
  <testcase classname="com.crm.qa.testcases.BaseUrlTest" name="T03_BaseUrlTittletest" time="2.245">
    <failure message="expected [software for customer relationship management] but found [Free CRM software for customer relationship management]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [software for customer relationship management] but found [Free CRM software for customer relationship management]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at com.crm.qa.testcases.BaseUrlTest.T03_BaseUrlTittletest(BaseUrlTest.java:50)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at com.crm.qa.testcases.TestRunner.main(TestRunner.java:36)
]]>
    </failure>
  </testcase> <!-- T03_BaseUrlTittletest -->
  <system-out/>
</testsuite> <!-- com.crm.qa.testcases.BaseUrlTest -->
